version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: finance_db
    environment:
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: financedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance_network


  backend:
    build: ./backend
    container_name: finance_backend
    environment:
      DATABASE_URL: postgresql://financeuser:financepass@postgres:5432/financedb
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance_network
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: finance_bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      API_URL: http://backend:8000
      DASHBOARD_URL: http://78.85.36.187:8050
    depends_on:
      - backend
    networks:
      - finance_network
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: finance_dashboard
    ports:
      - "8050:8050"
    depends_on:
      - backend
    networks:
      - finance_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  finance_network:
    driver: bridge
